export const weatherCondition = [
  {
    name: "CloudyDay",
    image: new URL("../assets/weatherConditions/CloudyDay.svg", import.meta.url)
      .href,
  },
  {
    name: "CloudyNight",
    image: new URL(
      "../assets/weatherConditions/CloudyNight.svg",
      import.meta.url
    ).href,
  },
  {
    name: "FogDay",
    image: new URL("../assets/weatherConditions/FogDay.svg", import.meta.url)
      .href,
  },
  {
    name: "FogNight",
    image: new URL("../assets/weatherConditions/FogNight.svg", import.meta.url)
      .href,
  },
  {
    name: "RainDay",
    image: new URL("../assets/weatherConditions/RainDay.svg", import.meta.url)
      .href,
  },
  {
    name: "RainNight",
    image: new URL("../assets/weatherConditions/RainNight.svg", import.meta.url)
      .href,
  },
  {
    name: "SnowDay",
    image: new URL("../assets/weatherConditions/SnowDay.svg", import.meta.url)
      .href,
  },
  {
    name: "SnowNight",
    image: new URL("../assets/weatherConditions/SnowNight.svg", import.meta.url)
      .href,
  },
  {
    name: "StormDay",
    image: new URL("../assets/weatherConditions/StormDay.svg", import.meta.url)
      .href,
  },
  {
    name: "StormNight",
    image: new URL(
      "../assets/weatherConditions/StormNight.svg",
      import.meta.url
    ).href,
  },
  {
    name: "SunnyDay",
    image: new URL("../assets/weatherConditions/SunnyDay.svg", import.meta.url)
      .href,
  },
  {
    name: "SunnyNight",
    image: new URL(
      "../assets/weatherConditions/SunnyNight.svg",
      import.meta.url
    ).href,
  },
];
